apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: utilbox
  name: utilbox
spec:
  containers:
  - args:
    - sleep
    - "600"
    image: busybox
    name: utilbox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
