apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-pod-new
  name: redis-pod-new
spec:
  containers:
  - image: redis
    name: redis-pod-new
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
