apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: demo
spec:
  releaseName: podinfo
  chart:
    git: https://github.com/myvelcn/helm-operator-get-started/tree/master/charts/podinfo
    ref: v3.x
    path: charts/podinfo
